import { useCallback, useEffect, useState } from 'react'
import { Check, CheckSquare, Clock3, Pencil, Plus, RefreshCw, Trash2, X } from 'lucide-react'
import { getApiError } from '../../../services/api'
import { tasksApi } from '../services/tasksApi'
import type { Task } from '../types/tasks'

const emptyForm = { title: '', note: '', due_date: '' }

export function TasksPage() {
  const [tasks, setTasks] = useState<Task[]>([]); const [form, setForm] = useState(emptyForm); const [editing, setEditing] = useState<Task | null>(null); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { setTasks(await tasksApi.getTasks()) } catch (err) { setError(getApiError(err)) } finally { setLoading(false) } }, [])
  // The effect loads server data when this screen opens.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { void load() }, [load])
  const openForm = (task?: Task) => { setEditing(task ?? null); setForm(task ? { title: task.title, note: task.note ?? '', due_date: task.due_date ?? '' } : emptyForm); setOpen(true) }
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form.title.trim()) return; setBusy(true); try { const payload = { title: form.title.trim(), note: form.note.trim() || null, due_date: form.due_date || null }; if (editing) await tasksApi.updateTask(editing.id, payload); else await tasksApi.createTask(payload); setOpen(false); await load() } catch (err) { setError(getApiError(err)) } finally { setBusy(false) } }
  const toggle = async (task: Task) => { try { await tasksApi.updateTask(task.id, { completed: !task.completed }); await load() } catch (err) { setError(getApiError(err)) } }
  const remove = async (task: Task) => { if (!window.confirm(`Xóa việc “${task.title}”?`)) return; try { await tasksApi.deleteTask(task.id); await load() } catch (err) { setError(getApiError(err)) } }
  return <div className="page-content"><div className="page-heading-row"><div><p className="eyebrow">Ghi chú & việc cần làm</p><h1>Việc cần làm</h1><p className="page-subtitle">Những việc chưa có thời gian cụ thể sẽ nằm ở đây.</p></div><button className="button-primary" onClick={() => openForm()}><Plus size={17} /> Thêm việc</button></div>{error && <div className="notice notice-error">{error}</div>}{loading ? <div className="card empty-state"><RefreshCw className="animate-spin" size={20} /> Đang tải danh sách…</div> : <div className="task-list">{tasks.length === 0 ? <div className="card empty-state"><CheckSquare size={30} /><strong>Chưa có việc nào</strong><span>Thêm một việc nhỏ để không bỏ quên.</span></div> : tasks.map((task) => <div className={`task-row${task.completed ? ' is-completed' : ''}`} key={task.id}><button className="task-check" aria-label={task.completed ? 'Đánh dấu chưa hoàn thành' : 'Đánh dấu hoàn thành'} onClick={() => void toggle(task)}>{task.completed && <Check size={16} />}</button><div className="task-copy"><strong>{task.title}</strong>{task.note && <span>{task.note}</span>}<small>{task.due_date ? <><Clock3 size={13} /> {task.due_date}</> : 'Không có thời gian cụ thể'}</small></div><div className="task-actions"><button className="icon-button" title="Sửa" aria-label="Sửa việc" onClick={() => openForm(task)}><Pencil size={16} /></button><button className="icon-button danger-icon" title="Xóa" aria-label="Xóa việc" onClick={() => void remove(task)}><Trash2 size={16} /></button></div></div>)}</div>}{open && <div className="modal-backdrop" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget) setOpen(false) }}><form className="modal-panel" onSubmit={(event) => void save(event)}><div className="modal-header"><div><p className="eyebrow">{editing ? 'Cập nhật' : 'Tạo mới'}</p><h2>{editing ? 'Sửa việc' : 'Thêm việc cần làm'}</h2></div><button type="button" className="icon-button" onClick={() => setOpen(false)} aria-label="Đóng"><X size={18} /></button></div><label className="form-label">Tên việc<input autoFocus className="field" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} placeholder="Ví dụ: Mua thuốc" required /></label><label className="form-label">Ghi chú<textarea className="field min-h-24" value={form.note} onChange={(event) => setForm({ ...form, note: event.target.value })} placeholder="Thêm thông tin nếu cần" /></label><label className="form-label">Ngày dự kiến <span className="form-hint">(không bắt buộc)</span><input className="field" type="date" value={form.due_date} onChange={(event) => setForm({ ...form, due_date: event.target.value })} /></label><div className="modal-footer"><button type="button" className="button-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="button-primary" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu việc'}</button></div></form></div>}</div>
}
