import { useState } from 'react'
import { ArrowDownLeft, ArrowUpRight, HandCoins, Pencil, Plus, Trash2 } from 'lucide-react'
import type { Debt, DebtDirection } from '../types/debt'
import { formatVnd } from '../../../utils/format'

interface Props { debts: Debt[]; onCreate: (payload: { person: string; direction: DebtDirection; amount: string; paid_amount: string; due_date: string | null; note: string | null }) => Promise<void>; onUpdate: (id: number, payload: Partial<Debt>) => Promise<void>; onDelete: (debt: Debt) => Promise<void> }

export function DebtList({ debts, onCreate, onUpdate, onDelete }: Props) {
  const [open, setOpen] = useState(false); const [editing, setEditing] = useState<Debt | null>(null); const [person, setPerson] = useState(''); const [direction, setDirection] = useState<DebtDirection>('OWED_BY_ME'); const [amount, setAmount] = useState(''); const [paid, setPaid] = useState('0'); const [note, setNote] = useState('')
  const start = (debt?: Debt) => { setEditing(debt ?? null); setPerson(debt?.person ?? ''); setDirection(debt?.direction ?? 'OWED_BY_ME'); setAmount(debt?.amount ?? ''); setPaid(debt?.paid_amount ?? '0'); setNote(debt?.note ?? ''); setOpen(true) }
  const save = async (event: React.FormEvent) => { event.preventDefault(); const payload = { person: person.trim(), direction, amount, paid_amount: paid || '0', due_date: editing?.due_date ?? null, note: note.trim() || null }; if (editing) await onUpdate(editing.id, payload); else await onCreate(payload); setOpen(false) }
  return <section className="card p-5"><div className="section-heading"><div><h3><HandCoins size={18} /> Khoản nợ</h3><p>Theo dõi tiền bạn cần trả hoặc sẽ nhận.</p></div><button className="button-secondary" onClick={() => start()}><Plus size={16} /> Thêm khoản nợ</button></div>{debts.length === 0 ? <div className="empty-inline">Chưa có khoản nợ nào.</div> : <div className="debt-list">{debts.map((debt) => { const remaining = Number(debt.amount) - Number(debt.paid_amount); const mine = debt.direction === 'OWED_BY_ME'; return <div className="debt-row" key={debt.id}><span className={`debt-icon ${mine ? 'is-out' : 'is-in'}`}>{mine ? <ArrowUpRight size={16} /> : <ArrowDownLeft size={16} />}</span><div className="debt-copy"><strong>{debt.person}</strong><small>{mine ? 'Bạn cần trả' : 'Bạn sẽ nhận'} · còn {formatVnd(remaining)}</small>{debt.note && <span>{debt.note}</span>}</div><strong className={mine ? 'text-rose-600' : 'text-emerald-600'}>{formatVnd(Number(debt.amount))}</strong><button className="icon-button" aria-label="Sửa khoản nợ" onClick={() => start(debt)}><Pencil size={15} /></button><button className="icon-button danger-icon" aria-label="Xóa khoản nợ" onClick={() => void onDelete(debt)}><Trash2 size={15} /></button></div> })}</div>}{open && <div className="modal-backdrop"><form className="modal-panel" onSubmit={(event) => void save(event)}><h2>{editing ? 'Sửa khoản nợ' : 'Thêm khoản nợ'}</h2><label className="form-label">Người liên quan<input className="field" value={person} onChange={(e) => setPerson(e.target.value)} required /></label><label className="form-label">Loại<select className="field" value={direction} onChange={(e) => setDirection(e.target.value as DebtDirection)}><option value="OWED_BY_ME">Tôi cần trả</option><option value="OWED_TO_ME">Tôi sẽ nhận</option></select></label><div className="form-grid-2"><label className="form-label">Tổng tiền<input className="field" type="number" min="0.01" value={amount} onChange={(e) => setAmount(e.target.value)} required /></label><label className="form-label">Đã thanh toán<input className="field" type="number" min="0" value={paid} onChange={(e) => setPaid(e.target.value)} /></label></div><label className="form-label">Ghi chú<textarea className="field" value={note} onChange={(e) => setNote(e.target.value)} /></label><div className="modal-footer"><button type="button" className="button-secondary" onClick={() => setOpen(false)}>Hủy</button><button className="button-primary">Lưu</button></div></form></div>}</section>
}
