import { Pencil, Trash2 } from 'lucide-react'
import type { Account, Transaction, TransactionCategory } from '../types/finance'
import { transactionLabels } from '../types/finance'
import { formatVnd } from '../../../utils/format'

export function TransactionTable({ transactions, accounts, categories, onEdit, onDelete }: { transactions: Transaction[]; accounts: Account[]; categories: TransactionCategory[]; onEdit: (transaction: Transaction) => void; onDelete: (transaction: Transaction) => void }) {
  const accountName = (id: number | null) => accounts.find((item) => item.id === id)?.name ?? '—'
  return <div className="card overflow-hidden"><div className="border-b border-slate-100 px-5 py-4"><h3 className="font-bold text-slate-800">Giao dịch gần đây</h3><p className="mt-0.5 text-xs text-slate-400">Các giao dịch mới nhất</p></div>{transactions.length === 0 ? <div className="p-8 text-center text-sm text-slate-400">Chưa có giao dịch phù hợp.</div> : <div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-50 text-xs font-bold text-slate-400"><tr><th className="px-5 py-3">Ngày</th><th className="px-5 py-3">Loại</th><th className="px-5 py-3">Danh mục / Mô tả</th><th className="px-5 py-3">Tài khoản</th><th className="px-5 py-3 text-right">Số tiền</th><th className="px-5 py-3" /></tr></thead><tbody className="divide-y divide-slate-100">{transactions.slice(0, 50).map((transaction) => { const category = categories.find((item) => item.id === transaction.category_id); const transfer = transaction.type === 'TRANSFER'; return <tr key={transaction.id} className="hover:bg-slate-50"><td className="px-5 py-3 text-slate-500">{new Intl.DateTimeFormat('vi-VN').format(new Date(`${transaction.transaction_date}T00:00:00`))}</td><td className="px-5 py-3"><span className={`rounded-full px-2 py-1 text-[11px] font-bold ${transaction.type === 'INCOME' ? 'bg-emerald-50 text-emerald-700' : transaction.type === 'EXPENSE' ? 'bg-rose-50 text-rose-700' : 'bg-blue-50 text-blue-700'}`}>{transactionLabels[transaction.type]}</span></td><td className="max-w-[230px] px-5 py-3"><p className="truncate font-semibold text-slate-700">{category?.name ?? (transfer ? 'Chuyển khoản' : 'Không phân loại')}</p><p className="truncate text-xs text-slate-400">{transaction.description || 'Không có mô tả'}</p></td><td className="px-5 py-3 text-slate-500">{accountName(transaction.account_id)}{transfer && <span className="text-xs"> → {accountName(transaction.related_account_id)}</span>}</td><td className={`px-5 py-3 text-right font-bold ${transaction.type === 'INCOME' ? 'text-emerald-600' : transaction.type === 'EXPENSE' ? 'text-rose-600' : 'text-blue-600'}`}>{transaction.type === 'INCOME' ? '+' : transaction.type === 'EXPENSE' ? '-' : ''}{formatVnd(Number(transaction.amount))}</td><td className="px-5 py-3"><div className="flex justify-end gap-1"><button className="rounded p-1.5 text-slate-400 hover:bg-slate-100 hover:text-blue-600" onClick={() => onEdit(transaction)} aria-label="Sửa giao dịch"><Pencil size={14} /></button><button className="rounded p-1.5 text-slate-400 hover:bg-rose-50 hover:text-rose-600" onClick={() => onDelete(transaction)} aria-label="Xóa giao dịch"><Trash2 size={14} /></button></div></td></tr> })}</tbody></table></div>}</div>
}
