import { useState } from 'react'
import { LoaderCircle, Send, Sparkles } from 'lucide-react'
import { getApiError } from '../../../services/api'
import { aiApi } from '../services/aiApi'

const quickActions = ['Tóm tắt hôm nay', 'Phân tích tuần này', 'Phân tích chi tiêu tháng này', 'Gợi ý lịch ngày mai', 'Đánh giá thói quen gần đây']
interface Message { role: 'user' | 'assistant'; content: string; domains?: string[] }

export function AIPage() {
  const [messages, setMessages] = useState<Message[]>([]); const [input, setInput] = useState(''); const [busy, setBusy] = useState(false)
  const send = async (question: string) => { const value = question.trim(); if (!value || busy) return; setMessages((current) => [...current, { role: 'user', content: value }]); setInput(''); setBusy(true); try { const response = await aiApi.chat(value); setMessages((current) => [...current, { role: 'assistant', content: response.answer, domains: response.context_domains }]) } catch (error) { setMessages((current) => [...current, { role: 'assistant', content: getApiError(error, 'Không thể kết nối Gemini. Hãy kiểm tra cấu hình trong Cài đặt.') }]) } finally { setBusy(false) } }
  return <div className="page-content"><div className="mx-auto max-w-4xl"><div className="mb-7"><p className="text-sm font-semibold text-blue-600">Trợ lý dữ liệu cá nhân</p><h2 className="mt-1 text-2xl font-bold text-slate-800">Gemini Assistant</h2><p className="mt-1 text-sm text-slate-500">Phân tích dữ liệu đã được Personal Manager tổng hợp. Gemini không thể sửa dữ liệu của bạn.</p></div><div className="mb-5 flex flex-wrap gap-2">{quickActions.map((action) => <button key={action} className="button-secondary" disabled={busy} onClick={() => void send(action)}>{action}</button>)}</div><section className="card flex min-h-[480px] flex-col p-5"><div className="flex-1 space-y-4 overflow-y-auto">{messages.length === 0 && <div className="grid min-h-[330px] place-items-center text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-xl bg-blue-50 text-blue-600"><Sparkles size={23} /></div><p className="mt-4 font-semibold text-slate-700">Hỏi về dữ liệu cá nhân của bạn</p><p className="mt-1 text-sm text-slate-400">Chỉ dữ liệu liên quan đến câu hỏi mới được gửi tới Gemini.</p></div></div>}{messages.map((message, index) => <div key={index} className={`flex ${message.role === 'user' ? 'justify-end' : 'justify-start'}`}><div className={`max-w-[82%] rounded-xl px-4 py-3 text-sm leading-6 ${message.role === 'user' ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-700'}`}><p className="whitespace-pre-wrap">{message.content}</p>{message.domains && <p className="mt-2 text-[10px] opacity-60">Ngữ cảnh: {message.domains.join(', ')}</p>}</div></div>)}{busy && <div className="flex items-center gap-2 text-sm text-slate-400"><LoaderCircle className="animate-spin" size={16} /> Đang phân tích…</div>}</div><form className="mt-5 flex gap-2 border-t border-slate-100 pt-4" onSubmit={(event) => { event.preventDefault(); void send(input) }}><input className="field flex-1" value={input} onChange={(event) => setInput(event.target.value)} placeholder="Hỏi về dữ liệu cá nhân của bạn…" maxLength={2000} /><button className="button-primary" disabled={busy || !input.trim()}><Send size={16} /> Gửi</button></form></section></div></div>
}
