import { useState } from 'react'
import { X } from 'lucide-react'
import type { BodyProfile, Food, MealType } from '../types/health'
import { activityLabels, goalLabels, mealLabels } from '../types/health'

function ModalHeader({ title, onClose }: { title: string; onClose: () => void }) { return <div className="flex items-center justify-between border-b border-slate-100 px-6 py-4"><h2 className="font-bold text-slate-800">{title}</h2><button type="button" onClick={onClose} className="text-slate-400 hover:text-slate-700" aria-label="Đóng"><X size={19} /></button></div> }
function Actions({ onClose, busy }: { onClose: () => void; busy: boolean }) { return <div className="flex justify-end gap-2 border-t border-slate-100 px-6 py-4"><button type="button" className="button-secondary" onClick={onClose}>Hủy</button><button type="submit" className="button-primary" disabled={busy}>{busy ? 'Đang lưu…' : 'Lưu'}</button></div> }

export function ProfileForm({ profile, onClose, onSubmit, busy }: { profile: BodyProfile | null; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void>; busy: boolean }) {
  const [height, setHeight] = useState(profile?.height_cm ?? ''); const [weight, setWeight] = useState(profile?.weight_kg ?? ''); const [age, setAge] = useState(String(profile?.age ?? '')); const [sex, setSex] = useState(profile?.sex ?? 'MALE'); const [activity, setActivity] = useState(profile?.activity_level ?? 'MODERATE'); const [goal, setGoal] = useState(profile?.goal ?? 'MAINTAIN')
  return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); void onSubmit({ height_cm: height, weight_kg: weight, age: Number(age), sex, activity_level: activity, goal }) }}><ModalHeader title={profile ? 'Cập nhật hồ sơ cơ thể' : 'Tạo hồ sơ sức khỏe'} onClose={onClose} /><div className="grid gap-4 px-6 py-5"><div className="grid grid-cols-2 gap-3"><div><label className="field-label" htmlFor="profile-height">Chiều cao (cm)</label><input id="profile-height" className="field" type="number" min="1" step="0.1" required value={height} onChange={(e) => setHeight(e.target.value)} /></div><div><label className="field-label" htmlFor="profile-weight">Cân nặng (kg)</label><input id="profile-weight" className="field" type="number" min="1" step="0.1" required value={weight} onChange={(e) => setWeight(e.target.value)} /></div></div><div className="grid grid-cols-2 gap-3"><div><label className="field-label" htmlFor="profile-age">Tuổi</label><input id="profile-age" className="field" type="number" min="1" required value={age} onChange={(e) => setAge(e.target.value)} /></div><div><label className="field-label" htmlFor="profile-sex">Giới tính</label><select id="profile-sex" className="field" value={sex} onChange={(e) => setSex(e.target.value as 'MALE' | 'FEMALE')}><option value="MALE">Nam</option><option value="FEMALE">Nữ</option></select></div></div><div><label className="field-label" htmlFor="profile-activity">Mức độ vận động</label><select id="profile-activity" className="field" value={activity} onChange={(e) => setActivity(e.target.value as BodyProfile['activity_level'])}>{Object.entries(activityLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><div><label className="field-label" htmlFor="profile-goal">Mục tiêu</label><select id="profile-goal" className="field" value={goal} onChange={(e) => setGoal(e.target.value as BodyProfile['goal'])}>{Object.entries(goalLabels).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></div><p className="text-xs leading-5 text-slate-400">Các chỉ số chỉ mang tính thông tin, không phải chẩn đoán y khoa.</p></div><Actions onClose={onClose} busy={busy} /></form></div>
}

export function MeasurementForm({ onClose, onSubmit, busy }: { onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void>; busy: boolean }) {
  const now = new Date(); now.setMinutes(now.getMinutes() - now.getTimezoneOffset()); const [weight, setWeight] = useState(''); const [waist, setWaist] = useState(''); const [recordedAt, setRecordedAt] = useState(now.toISOString().slice(0, 16)); const [note, setNote] = useState('')
  return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); void onSubmit({ weight_kg: weight, waist_cm: waist || null, recorded_at: new Date(recordedAt).toISOString(), note: note || null }) }}><ModalHeader title="Ghi cân nặng" onClose={onClose} /><div className="grid gap-4 px-6 py-5"><div className="grid grid-cols-2 gap-3"><div><label className="field-label" htmlFor="measurement-weight">Cân nặng (kg)</label><input id="measurement-weight" className="field" type="number" min="1" step="0.1" required value={weight} onChange={(e) => setWeight(e.target.value)} /></div><div><label className="field-label" htmlFor="measurement-waist">Vòng eo (cm)</label><input id="measurement-waist" className="field" type="number" min="1" step="0.1" value={waist} onChange={(e) => setWaist(e.target.value)} /></div></div><div><label className="field-label" htmlFor="measurement-date">Thời điểm</label><input id="measurement-date" className="field" type="datetime-local" required value={recordedAt} onChange={(e) => setRecordedAt(e.target.value)} /></div><div><label className="field-label" htmlFor="measurement-note">Ghi chú</label><input id="measurement-note" className="field" value={note} onChange={(e) => setNote(e.target.value)} /></div></div><Actions onClose={onClose} busy={busy} /></form></div>
}

export function DailyHealthForm({ date, initial, onClose, onSubmit, busy }: { date: string; initial: { sleep_hours: string | null; water_ml: number | null; steps: number | null; exercise_type: string | null; exercise_minutes: number | null; note: string | null } | null; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void>; busy: boolean }) {
  const [sleep, setSleep] = useState(initial?.sleep_hours ?? ''); const [water, setWater] = useState(String(initial?.water_ml ?? '')); const [steps, setSteps] = useState(String(initial?.steps ?? '')); const [exercise, setExercise] = useState(initial?.exercise_type ?? ''); const [minutes, setMinutes] = useState(String(initial?.exercise_minutes ?? '')); const [note, setNote] = useState(initial?.note ?? '')
  const optionalNumber = (value: string) => value === '' ? null : Number(value)
  return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); void onSubmit({ sleep_hours: sleep || null, water_ml: optionalNumber(water), steps: optionalNumber(steps), exercise_type: exercise || null, exercise_minutes: optionalNumber(minutes), note: note || null }) }}><ModalHeader title={`Theo dõi ngày ${date.split('-').reverse().join('/')}`} onClose={onClose} /><div className="grid gap-4 px-6 py-5"><div className="grid grid-cols-3 gap-3"><div><label className="field-label" htmlFor="daily-sleep">Ngủ (giờ)</label><input id="daily-sleep" className="field" type="number" min="0" max="24" step="0.1" value={sleep} onChange={(e) => setSleep(e.target.value)} /></div><div><label className="field-label" htmlFor="daily-water">Nước (ml)</label><input id="daily-water" className="field" type="number" min="0" value={water} onChange={(e) => setWater(e.target.value)} /></div><div><label className="field-label" htmlFor="daily-steps">Bước chân</label><input id="daily-steps" className="field" type="number" min="0" value={steps} onChange={(e) => setSteps(e.target.value)} /></div></div><div className="grid grid-cols-2 gap-3"><div><label className="field-label" htmlFor="daily-exercise">Loại vận động</label><input id="daily-exercise" className="field" value={exercise} onChange={(e) => setExercise(e.target.value)} placeholder="Ví dụ: Cầu lông" /></div><div><label className="field-label" htmlFor="daily-minutes">Thời gian (phút)</label><input id="daily-minutes" className="field" type="number" min="0" value={minutes} onChange={(e) => setMinutes(e.target.value)} /></div></div><div><label className="field-label" htmlFor="daily-note">Ghi chú</label><textarea id="daily-note" className="field min-h-20" value={note} onChange={(e) => setNote(e.target.value)} /></div></div><Actions onClose={onClose} busy={busy} /></form></div>
}

export function FoodForm({ editing, onClose, onSubmit, busy }: { editing: Food | null; onClose: () => void; onSubmit: (payload: Record<string, unknown>, id?: number) => Promise<void>; busy: boolean }) {
  const [name, setName] = useState(editing?.name ?? ''); const [serving, setServing] = useState(editing?.serving_quantity ?? '100'); const [unit, setUnit] = useState(editing?.serving_unit ?? 'g'); const [calories, setCalories] = useState(editing?.calories ?? ''); const [protein, setProtein] = useState(editing?.protein ?? '0'); const [carbs, setCarbs] = useState(editing?.carbs ?? '0'); const [fat, setFat] = useState(editing?.fat ?? '0')
  return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); void onSubmit({ name, serving_quantity: serving, serving_unit: unit, calories, protein, carbs, fat }, editing?.id) }}><ModalHeader title={editing ? 'Sửa thực phẩm' : 'Tạo thực phẩm'} onClose={onClose} /><div className="grid gap-4 px-6 py-5"><div><label className="field-label" htmlFor="food-name">Tên thực phẩm</label><input id="food-name" className="field" required value={name} onChange={(e) => setName(e.target.value)} placeholder="Ví dụ: Ức gà" /></div><div className="grid grid-cols-2 gap-3"><div><label className="field-label" htmlFor="food-serving">Khẩu phần</label><input id="food-serving" className="field" type="number" min="0.01" step="0.01" required value={serving} onChange={(e) => setServing(e.target.value)} /></div><div><label className="field-label" htmlFor="food-unit">Đơn vị</label><input id="food-unit" className="field" required value={unit} onChange={(e) => setUnit(e.target.value)} /></div></div><div className="grid grid-cols-4 gap-3"><div><label className="field-label" htmlFor="food-calories">Kcal</label><input id="food-calories" className="field" type="number" min="0" step="0.1" required value={calories} onChange={(e) => setCalories(e.target.value)} /></div><div><label className="field-label" htmlFor="food-protein">Protein</label><input id="food-protein" className="field" type="number" min="0" step="0.1" value={protein} onChange={(e) => setProtein(e.target.value)} /></div><div><label className="field-label" htmlFor="food-carbs">Carbs</label><input id="food-carbs" className="field" type="number" min="0" step="0.1" value={carbs} onChange={(e) => setCarbs(e.target.value)} /></div><div><label className="field-label" htmlFor="food-fat">Fat</label><input id="food-fat" className="field" type="number" min="0" step="0.1" value={fat} onChange={(e) => setFat(e.target.value)} /></div></div></div><Actions onClose={onClose} busy={busy} /></form></div>
}

export function FoodLogForm({ foods, date, onClose, onSubmit, busy }: { foods: Food[]; date: string; onClose: () => void; onSubmit: (payload: Record<string, unknown>) => Promise<void>; busy: boolean }) {
  const [search, setSearch] = useState(''); const visible = foods.filter((food) => food.name.toLowerCase().includes(search.toLowerCase())); const [foodId, setFoodId] = useState(String(foods[0]?.id ?? '')); const [quantity, setQuantity] = useState(''); const [meal, setMeal] = useState<MealType>('BREAKFAST'); const selected = foods.find((food) => String(food.id) === foodId)
  return <div className="modal-backdrop"><form className="modal" onSubmit={(event) => { event.preventDefault(); void onSubmit({ food_id: Number(foodId), quantity, meal_type: meal, logged_date: date }) }}><ModalHeader title="Thêm thực phẩm đã ăn" onClose={onClose} /><div className="grid gap-4 px-6 py-5"><div><label className="field-label" htmlFor="food-search">Tìm thực phẩm</label><input id="food-search" className="field" value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Nhập tên thực phẩm" /></div><div><label className="field-label" htmlFor="food-select">Thực phẩm</label><select id="food-select" className="field" required value={foodId} onChange={(e) => setFoodId(e.target.value)}>{visible.map((food) => <option key={food.id} value={food.id}>{food.name} · {food.calories} kcal/{food.serving_quantity}{food.serving_unit}</option>)}</select></div><div className="grid grid-cols-2 gap-3"><div><label className="field-label" htmlFor="log-quantity">Số lượng {selected ? `(${selected.serving_unit})` : ''}</label><input id="log-quantity" className="field" type="number" min="0.01" step="0.01" required value={quantity} onChange={(e) => setQuantity(e.target.value)} /></div><div><label className="field-label" htmlFor="log-meal">Bữa ăn</label><select id="log-meal" className="field" value={meal} onChange={(e) => setMeal(e.target.value as MealType)}>{Object.entries(mealLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div></div></div><Actions onClose={onClose} busy={busy} /></form></div>
}
